services:
  app:
    environment:
      - PROJECT_PATH=/project/LCNet
      # prevents python creating .pyc files at runtime
      - PYTHONDONTWRITEBYTECODE=1
      # compile python dependencies into .pyc files
      - UV_COMPILE_BYTECODE=1
      - PYTHONDEVMODE=0
      - TZ=Asia/Taipei
    build:
      context: .
      target: prod
      # secrets:
      #   - GIT_AUTH_TOKEN
      args:
        - PROJECT_PATH=/project/LCNet
        - TZ=Asia/Taipei
    shm_size: 6G
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

# secrets:
#   GIT_AUTH_TOKEN:
#     environment: GIT_AUTH_TOKEN

